apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teleport
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/justk8s/deployments'
    targetRevision: HEAD
    path: charts/teleport
    helm:
      valueFiles:
        - values.yaml
        - values-justk8s.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: teleport
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
