apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mukeshkuiry/deployments'
    targetRevision: HEAD
    path: 'installations/example-installation/argocd'
    helm:
      valueFiles:
        - values.yaml
        - values-justk8s.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
